#!/bin/bash

if [[ "$1" == "show" ]] && [[ "$2" == "config" ]]; then
  cat <<EOF
Configuration data as of 2025-09-16T10:59:04
SlurmdSpoolDir          = /tmp/spool/slurmd (default)
TmpFS                   = /tmp (default)
Slurmctld(primary) at zinal-slurmctl is UP
EOF
fi
